{% set version = "2.6.2" %}

package:
  name: glances
  version: {{ version }}

source:
  fn: Glances-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/G/Glances/Glances-{{ version }}.tar.gz
  sha256: 0024461fade788e9b7411720fca7835e2971d0f41f240e396a53d975e1d5640d

build:
  number: 0
  entry_points:
    - glances=glances:main
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
    - psutil >=2.0.0

  run:
    - python
    - psutil >=2.0.0

test:
  imports:
    - glances

  commands:
    - glances --help

about:
  home: https://github.com/nicolargo/glances
  license: LGPL 3
  summary: 'A cross-platform curses-based monitoring tool'

extra:
  recipe-maintainers:
    - jakirkham
