{% set version = "3.1.4" %}

package:
  name: glances
  version: {{ version }}

source:
  fn: Glances-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/G/Glances/Glances-{{ version }}.tar.gz
  sha256: 98de0155649a7d847b67ef6f06875c5df54edfed30e2766fe743a5bbd73b8435

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - glances = glances:main

requirements:
  build:
    - python
    - pip

  run:
    - python
    - psutil >=5.3.0
    - future

test:
  requires:
    - pip

  imports:
    - glances

  commands:
    - pip check
    - glances --help

about:
  home: https://github.com/nicolargo/glances
  license: LGPL 3
  license_family: LGPL
  license_file: COPYING
  summary: A cross-platform curses-based monitoring tool

extra:
  recipe-maintainers:
    - jakirkham
