{% set version = "3.1.1" %}

package:
  name: glances
  version: {{ version }}

source:
  fn: Glances-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/G/Glances/Glances-{{ version }}.tar.gz
  sha256: 2856a8519d08051ab65d118208226e60971453f6365712c3f75347acff7b411e

build:
  number: 0
  noarch: python
  script: python setup.py install --single-version-externally-managed --record=record.txt
  entry_points:
    - glances = glances:main

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - psutil >=5.3.0

test:
  imports:
    - glances

  commands:
    - glances --help

about:
  home: https://github.com/nicolargo/glances
  license: LGPL 3
  license_family: LGPL
  license_file: COPYING
  summary: 'A cross-platform curses-based monitoring tool'

extra:
  recipe-maintainers:
    - jakirkham
