{% set version = "2.8.8" %}

package:
  name: glances
  version: {{ version }}

source:
  fn: Glances-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/G/Glances/Glances-{{ version }}.tar.gz
  sha256: 094c1b430ef6bac858b60de8934b0155b54b4a229346370d2423bdac2267a1ca

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt
  entry_points:
    - glances=glances:main

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - psutil >=2.0.0

test:
  imports:
    - glances

  commands:
    - glances --help

about:
  home: https://github.com/nicolargo/glances
  license: LGPL 3
  license_family: LGPL
  license_file: COPYING
  summary: 'A cross-platform curses-based monitoring tool'

extra:
  recipe-maintainers:
    - jakirkham
