travis:
  secure:
    BINSTAR_TOKEN: VMvFdHlRqJ6Iep5B86Eb5GAhoxljizfgtfyq0cEJRSVaUQGCz+CZqcCIzEuavJDR4V+Iz+X7M8sHvhwidE/Trm9/g+sUicWVY0y77ZIOs/i7FjWNdHtJDDUxbgYxFDgLWI4OOeL3/PAqgaOeRcfXQEZfRLHUAJSAFqO8M0sUWK8Me5T+eSX2qVekRG2AICyZjzoolkiy8Jrv92lFaVfm+fz6fS3tja9QikFtrPKI4QY6ciXMUv8RN9G0HWLaTVRwAa2MvOqq5ddhLct2f4ZEaRykZjwrGE5xDSFDxwZdK2ohNTEpyGT6PC0MMFzFKP+Y6Qi1FDqNjElPPg6qz2QjA9UQmQT4KxmCdZOxkTGSBQUBUO0oFDsPOmbwzs+DO3zax+HF3H/4kfjacN786Q3t37bJ7LF+qly+hMDq+KXjWD1eDX6tg/nObyzIpSOB0/fxfqcXKJLfzB1/oEhUnuK6oAQfxPYyO42iMnrng9rNsuxEO1MOG9947rY4R7dEWG4lFwavT4ll1hkuG4oCkCXrk6RKnNzuZmO7hVASo92oC2pxx6YvVmiEc+RpXWhGncXFpiXmM0pZQtqGOvaORMof1lX+Dzf2GRFoxDdZmbeie5IqnsjhZwZKlzXUefkzmbHilKUvL2EwDgv0BoF7PWo07YSK+ivZF+wnxnXnapFMylw=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
