travis:
  secure:
    BINSTAR_TOKEN: kMQj/Fhr3s/FD4ECdabXPvEg53kP9ldFZhGoVXss8J2tig4zg6QRUkIKyyN0k58m1rO7g42GBkLrZ4jtq0eGx0O9X0+63vNPXyWysycn5jdZajWXvbuwcRwUqjy49aY3ZSB/hXd34D0KsOGulfR9K5p8TGfuwuFUXd0p1PT3v22aIegqiYqwkVaWrUNQBjpwykQcdgkWpl3jiAyxekGDw9hdse2I+dGxL0jinz3SU++bO/5kuLfS66H/dUlljAOCrWUUpp3dmVdEdWzNGFEVtYEE5KF3GBMhaNPJHVKREQsTAzEKyyjGB9kiKRp7oM/JVReBSa3OjlQahheERYmakyBLe3wGuCPU6pH+MLF9BLlcllmTvKiNEFwTvtYXi5CrxHLWuqC/BLMlKVKxRGz8XCZkLs5oiDptP7u2ECJ5H7lGMeQJn+9qvgNiaWZj4OqZ9SPZbtuDc3UaW+feG+vfjs+75xrFHyolbq1Znwrm1ELaRx4P4Fw03CXaq2kNX4X27rfOJHivOZfoSP615XzbXQrLz4whEeNvvX81hExmZKvLntmx4u6unBoRY5Qs3upL7e8UoF1W3TbRH+YlEMoKX2husP8E5LdN00+bu2OZVCowV64xY+PodwHptQcTwCXvGzPy5nslp4WMHUjSkt9EdWTKuXBaW0PBi8szQY/WVBg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
