travis:
  secure:
    BINSTAR_TOKEN: xnuxjpoUYXFUHl5HH2pwo+RFVXm7MT3+SOEeGXDLea8FMkjP7JKNRGV3qat/0uEi67piG1BGd3pb+7xO2WZ/zGZWmLu+rVQymprRoKA1S1kp3yfrwD0xQ4AXn4ljVbI7mO0IePqJOy1N0dA7DUQPQDHRfvjDWmSY3vjtmy1wOfQ1j3L+PlzVsSDWwcl3EyS4XjsHwF76w2Hdt2pCgSpzpUtIeqKp4bYyFSVd6WpV3upuOqWHaCOupzBHIOf8KkVSKXp6nDQOZIcgqk0hkiijSdfQLK4C9mZxPO91jekhVTzQseMHUPmq2X+5DoMaZB2JpH4Jf4GlM4Aig8Efx0xCGvwVMoktA3dS0CYZP/YZpSfbz9lAJbYB3xnIJ+QzCU1NtRiaFfzGxow+x823ZG0+1dQAAvUSskHsK53dqR4CzapSXQUiH0hroxOe+wkG3d14jHO6afpufMy1qejJ8pO+ZKbigxmTAfzRv6OXoDZAYYZfX/iTdComtYa+2/2QoBWWR3Ty0VWyYron8Ax0CFP44LL8PZJJFUNZAwTX1oKfdEsn+L1H+LKOxzBSM0QvVvI5ZVbbfhbLnCfxhwsiRTGcxw/TUmNHxuoDCMiAjmJvceP6D0t5BbXqBv3la9qrh+VM/lHnLNrx71b58eqMiOTDzum6eM87F3jRJDU8MZS4XEc=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
