travis:
  secure:
    BINSTAR_TOKEN: dy9h6Q8hUb86aRrBL+FUy3ioM3rdfgt6lqijDx7ckiy5JoDkt45kPlu+m3bRaAXpwAugLb2367kwTTPSTezXQRmvSq1IMeIbL91XOCpZXwQX/mtr9Z78llHuQDVOoDmhYpsQea4Dd+wNQXYAdyOgm02bI4Swoh080e1hzqkdK8qqNRQ1xguG2mgPvVT75i8x7lK5PSB/bL3abOLkA9onmXaCzUGXa+xgbV2lqDq33umZvgc2Ika06c1znufv7hO/+OJ+YeV+Fit0o3+fv8d14YNjNi4X81RcOXlaikTdfrodBjlFAa0BxcXlzzo9f8qlSJK7PUv9ebvBb5sDVhu83f0AJqfoHHCvGlFj4Xr6/EcX4pF66jRe3aZyFFgQNj0K228Zb0JiqxuLAUuSkz8iC+noBU+xoD0KVahtts+7uHLuDZOdYgAiuNueW2FvUKQRhqG/UaaYQxCKqwId5/6RIBSHHmkqzmelmdlxYKCtwNhZrdIxe9mP+OwnhHtUnJav7F95CD+C6+RQkhapBG4LLuLElWPjQ019ZGthEGY6+zAJc4S4bATnpmhcQapp6S+iFfpwbr4mYwDj8xwoPHKjdwp01tbw64gY4j0Ruu70y3pOLV5x19Iip7OsV3ttpSP/vsRDOWU04LPT2s0Tvm42jcmrIk/oYrubH1g4JNMQH1s=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
